import React, { ReactNode } from 'react'
import Head from 'next/head'

type Props = {
    children: ReactNode
}
const Layout = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>BSC Web App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <h1>This is the layout</h1>
            <div>{children}</div>
        </>
    )
}

export default Layout
